### PR TITLE
Add Get user status

### PR DESCRIPTION
**Pull request by BrunoSpy**
https://api.mattermost.com/#tag/status%2Fpaths%2F~1users~1%7Buser_id%7D~1status%2Fget

### CODE REVIEW

**Comment by gnello** [comment]
Thanks for your contribution!

There are a little things that need to be changed: `self::$endpoint . '/users/'` it's a repetition because the resource `'/users'` it's already defined in `self::$endpoint,` but thanks to you I've noticed the same thing in the method revokeToken! 
Plus could you implement the CamelCase standard for parameters (so `$userid` becames `$userId`)?

Thanks!

**Comment by gnello** [comment]
Great!
One last thing: in getUserStatusesById there is a double '/' in `self::$endpoint . '/' . '/status/ids'`, could you fix it?

Thanks!

**Comment by gnello** [comment]
Thanks again!

**Comment by BrunoSpy** [comment]
Thx for the merge and thx for the great work, your driver is clean and very usefull !

**Comment by gnello** [comment]
I'm glad you like it 😃 thanks again

**Pull request merged**
